title: MinStack
description: Backend engineering notes by Gyumin Hwangbo
baseurl: ""
url: "https://minstack.pages.dev"
cloudflare_site_url: "https://minstack.pages.dev"
cloudflare_build: true
permalink: pretty
favicon_ico: "/assets/img/favicons/minstack.svg"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

ga_tracking: G-97D062Z6YJ
ga_tracking_anonymize_ip: true

adsense:
  client: "ca-pub-6088017773958522"
  post_slot: "7035619504"
